[phases.setup]
nixPkgs = ['...', 'playwright-driver', 'chromium']

[phases.install]
cmds = [
  'pip install -r requirements.txt',
  'playwright install chromium --with-deps'
]

[start]
cmd = 'celery -A worker.celery_app worker --loglevel=info --concurrency=1'

[variables]
PYTHONUNBUFFERED = '1'